### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by mkaraev** [mk12/sicp#1]
Hello, first of all, thank you so much for your work and publishing this repository.
I have a question about your code. I'm learning SICP right now and faced the issue that Racket doesn't have the`parallel-execute` procedure. How did you implement it?
https://github.com/mk12/sicp/blob/750f8491683035d4d8f7b1c11d2f432b259fc6eb/src/sicp/chapter-3.ss#L1983
Thank you in advance.

**Comment by mk12** [comment]
Sorry for the delay, not sure why I didn't see this until now. `parallel-execute` is one of the procedures I implement separately for each Scheme implementation, as described in https://mk12.github.io/sicp/exercise/language.html#built-ins. Here is the Racket implementation:

https://github.com/mk12/sicp/blob/750f8491683035d4d8f7b1c11d2f432b259fc6eb/src/compat/racket/src/compat.ss#L46-L53

You can find the documentation for `thread` and `thread-wait` at https://docs.racket-lang.org/reference/threads.html.
